/**
 * React Query 配置
 * 统一的查询客户端配置，包括缓存策略、重试机制等
 */

import { QueryClient } from '@tanstack/react-query';

/**
 * 默认的查询配置
 */
export const defaultQueryOptions = {
  queries: {
    // 数据过期时间：5分钟
    staleTime: 5 * 60 * 1000,
    // 缓存保留时间：30分钟
    gcTime: 30 * 60 * 1000,
    // 重试次数
    retry: 2,
    // 重试延迟
    retryDelay: (attemptIndex: number) => Math.min(1000 * 2 ** attemptIndex, 10000),
    // 窗口重新聚焦时不自动重新获取（避免频繁请求）
    refetchOnWindowFocus: false,
    // 网络重连时重新获取
    refetchOnReconnect: true,
  },
  mutations: {
    // mutation 重试次数
    retry: 1,
  },
};

/**
 * 创建 QueryClient 实例
 */
export function createQueryClient() {
  return new QueryClient({
    defaultOptions: defaultQueryOptions,
  });
}

/**
 * Query Keys 常量
 * 统一管理所有查询的 key，便于缓存失效和调试
 */
export const queryKeys = {
  // 交易相关
  transactions: {
    all: ['transactions'] as const,
    list: (params?: { month?: string; range?: string; startDate?: string; endDate?: string }) =>
      ['transactions', 'list', params] as const,
    detail: (id: string) => ['transactions', 'detail', id] as const,
    todayAutoGenerated: () => ['transactions', 'today-auto-generated'] as const,
  },

  // 分类相关
  categories: {
    all: ['categories'] as const,
    list: (filter?: { is_active?: boolean }) => ['categories', 'list', filter] as const,
    subcategories: (categoryKey?: string) => ['categories', 'subcategories', categoryKey] as const,
    merchants: (limit?: number) => ['categories', 'merchants', limit] as const,
  },

  // 支付方式
  paymentMethods: {
    all: ['payment-methods'] as const,
    list: () => ['payment-methods', 'list'] as const,
  },

  // 预算相关
  budgets: {
    all: ['budgets'] as const,
    status: (params?: { year?: number; month?: number }) => ['budgets', 'status', params] as const,
    summary: (params?: { year?: number; month?: number }) => ['budgets', 'summary', params] as const,
    suggestions: () => ['budgets', 'suggestions'] as const,
  },

  // 定期支出
  recurringExpenses: {
    all: ['recurring-expenses'] as const,
    list: () => ['recurring-expenses', 'list'] as const,
    detail: (id: string) => ['recurring-expenses', 'detail', id] as const,
    history: () => ['recurring-expenses', 'history'] as const,
  },

  // 周报告
  weeklyReports: {
    all: ['weekly-reports'] as const,
    list: () => ['weekly-reports', 'list'] as const,
    detail: (id: string) => ['weekly-reports', 'detail', id] as const,
    latest: () => ['weekly-reports', 'latest'] as const,
  },

  // 常用备注
  commonNotes: {
    all: ['common-notes'] as const,
    list: (limit?: number) => ['common-notes', 'list', limit] as const,
    search: (keyword: string) => ['common-notes', 'search', keyword] as const,
  },

  // AI 相关
  ai: {
    prediction: (params: { type: string; [key: string]: unknown }) => ['ai', 'prediction', params] as const,
    analysis: (month?: string) => ['ai', 'analysis', month] as const,
    suggestions: (params?: unknown) => ['ai', 'suggestions', params] as const,
  },

  // 系统管理
  admin: {
    logs: (params?: { page?: number; level?: string }) => ['admin', 'logs', params] as const,
    cron: () => ['admin', 'cron'] as const,
  },
} as const;
