'use client';

/**
 * 交易相关 React Query Hooks
 */

import {
  useQuery,
  useMutation,
  useQueryClient,
  type UseMutationOptions,
} from '@tanstack/react-query';
import { queryKeys } from '../queryClient';
import {
  transactionsApi,
  type TransactionListParams,
  type CreateTransactionParams,
  type UpdateTransactionParams,
} from '../services/transactions';
import { applyTransactionWriteEffects } from '../transactionWriteEffects';
import type { Transaction } from '@/types/domain/transaction';

type MutationCallbacks<TData, TVariables> = Pick<
  UseMutationOptions<TData, Error, TVariables>,
  'onSuccess' | 'onError'
>;

type TransactionWriteEffectOptions = {
  clearCommonNotesCache?: boolean;
  revalidateServer?: boolean;
};

type CreateTransactionHookOptions = MutationCallbacks<Transaction, CreateTransactionParams> & {
  effectOptions?: TransactionWriteEffectOptions;
};

/**
 * 获取交易列表
 */
export function useTransactions(params?: TransactionListParams) {
  return useQuery({
    queryKey: queryKeys.transactions.list(params),
    queryFn: () => transactionsApi.list(params),
  });
}

/**
 * 获取单个交易
 */
export function useTransaction(id: string) {
  return useQuery({
    queryKey: queryKeys.transactions.detail(id),
    queryFn: () => transactionsApi.get(id),
    enabled: !!id,
  });
}

/**
 * 获取今日自动生成的交易
 */
export function useTodayAutoGeneratedTransactions() {
  return useQuery({
    queryKey: queryKeys.transactions.todayAutoGenerated(),
    queryFn: () => transactionsApi.getTodayAutoGenerated(),
  });
}

/**
 * 创建交易
 */
export function useCreateTransaction(
  options?: CreateTransactionHookOptions
) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data: CreateTransactionParams) => transactionsApi.create(data),
    onSuccess: (newTransaction, variables, onMutateResult, context) => {
      applyTransactionWriteEffects({
        action: 'create',
        queryClient,
        transactionId: newTransaction.id,
        payload: newTransaction,
        clearCommonNotesCache:
          options?.effectOptions?.clearCommonNotesCache ?? Boolean(newTransaction.note?.trim()),
        revalidateServer: options?.effectOptions?.revalidateServer ?? false,
      });
      options?.onSuccess?.(newTransaction, variables, onMutateResult, context);
    },
    onError: options?.onError,
  });
}

/**
 * 更新交易
 */
export function useUpdateTransaction(
  options?: MutationCallbacks<Transaction, UpdateTransactionParams>
) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data: UpdateTransactionParams) => transactionsApi.update(data),
    onSuccess: (updatedTransaction, variables, onMutateResult, context) => {
      applyTransactionWriteEffects({
        action: 'update',
        queryClient,
        transactionId: variables.id,
        payload: updatedTransaction,
      });
      options?.onSuccess?.(updatedTransaction, variables, onMutateResult, context);
    },
    onError: options?.onError,
  });
}

/**
 * 删除交易
 */
export function useDeleteTransaction(
  options?: MutationCallbacks<void, string>
) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (id: string) => transactionsApi.delete(id),
    onSuccess: (_, id, onMutateResult, context) => {
      applyTransactionWriteEffects({
        action: 'delete',
        queryClient,
        transactionId: id,
      });
      options?.onSuccess?.(undefined, id, onMutateResult, context);
    },
    onError: options?.onError,
  });
}

/**
 * 恢复已删除的交易
 */
export function useRestoreTransaction(
  options?: MutationCallbacks<Transaction, string>
) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (id: string) => transactionsApi.restore(id),
    onSuccess: (restoredTransaction, id, onMutateResult, context) => {
      applyTransactionWriteEffects({
        action: 'restore',
        queryClient,
        transactionId: id,
        payload: restoredTransaction,
      });
      options?.onSuccess?.(restoredTransaction, id, onMutateResult, context);
    },
    onError: options?.onError,
  });
}
