'use client';

/**
 * 交易相关 React Query Hooks
 */

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { queryKeys } from '../queryClient';
import {
  transactionsApi,
  type TransactionListParams,
  type CreateTransactionParams,
  type UpdateTransactionParams,
} from '../services/transactions';
import { applyTransactionWriteEffects } from '../transactionWriteEffects';

/**
 * 获取交易列表
 */
export function useTransactions(params?: TransactionListParams) {
  return useQuery({
    queryKey: queryKeys.transactions.list(params),
    queryFn: () => transactionsApi.list(params),
  });
}

/**
 * 获取单个交易
 */
export function useTransaction(id: string) {
  return useQuery({
    queryKey: queryKeys.transactions.detail(id),
    queryFn: () => transactionsApi.get(id),
    enabled: !!id,
  });
}

/**
 * 获取今日自动生成的交易
 */
export function useTodayAutoGeneratedTransactions() {
  return useQuery({
    queryKey: queryKeys.transactions.todayAutoGenerated(),
    queryFn: () => transactionsApi.getTodayAutoGenerated(),
  });
}

/**
 * 创建交易
 */
export function useCreateTransaction() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data: CreateTransactionParams) => transactionsApi.create(data),
    onSuccess: (newTransaction) => {
      applyTransactionWriteEffects({
        action: 'create',
        queryClient,
        transactionId: newTransaction.id,
        payload: newTransaction,
        clearCommonNotesCache: Boolean(newTransaction.note?.trim()),
      });
    },
  });
}

/**
 * 更新交易
 */
export function useUpdateTransaction() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data: UpdateTransactionParams) => transactionsApi.update(data),
    onSuccess: (updatedTransaction, variables) => {
      applyTransactionWriteEffects({
        action: 'update',
        queryClient,
        transactionId: variables.id,
        payload: updatedTransaction,
      });
    },
  });
}

/**
 * 删除交易
 */
export function useDeleteTransaction() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (id: string) => transactionsApi.delete(id),
    onSuccess: (_, id) => {
      applyTransactionWriteEffects({
        action: 'delete',
        queryClient,
        transactionId: id,
      });
    },
  });
}

/**
 * 恢复已删除的交易
 */
export function useRestoreTransaction() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (id: string) => transactionsApi.restore(id),
    onSuccess: (restoredTransaction, id) => {
      applyTransactionWriteEffects({
        action: 'restore',
        queryClient,
        transactionId: id,
        payload: restoredTransaction,
      });
    },
  });
}
