import { NextResponse } from 'next/server';
import { getPrismaClient } from '@/lib/clients/db';
import { withErrorHandler } from '@/lib/utils/apiErrorHandler';

export const GET = withErrorHandler(async () => {
  const today = new Date().toISOString().split('T')[0];

  // 查询今天自动生成的交易记录数量
  const prisma = getPrismaClient();
  const count = await prisma.transactions.count({
    where: {
      date: today,
      is_auto_generated: true,
      deleted_at: null,
    },
  });

  return NextResponse.json({
    date: today,
    count: count,
    hasAutoGenerated: count > 0
  });
});