import { NextRequest, NextResponse } from 'next/server';
import { supabase } from '@/lib/clients/supabase/client';
import { withErrorHandler, ApiError } from '@/lib/utils/apiErrorHandler';

export const GET = withErrorHandler(async (request: NextRequest) => {
  const today = new Date().toISOString().split('T')[0];

  // 查询今天自动生成的交易记录数量
  const { count, error } = await supabase
    .from('transactions')
    .select('*', { count: 'exact', head: true })
    .eq('date', today)
    .eq('is_auto_generated', true);

  if (error) {
    throw new ApiError('查询今日自动生成记录失败', 500);
  }

  return NextResponse.json({
    date: today,
    count: count || 0,
    hasAutoGenerated: (count || 0) > 0
  });
});