import { NextRequest, NextResponse } from 'next/server';
import { supabase } from '@/lib/clients/supabase/client';

export async function GET(request: NextRequest) {
  try {
    const today = new Date().toISOString().split('T')[0];

    // 查询今天自动生成的交易记录数量
    const { count, error } = await supabase
      .from('transactions')
      .select('*', { count: 'exact', head: true })
      .eq('date', today)
      .eq('is_auto_generated', true);

    if (error) {
      console.error('查询今日自动生成记录失败:', error);
      return NextResponse.json(
        { error: '查询失败' },
        { status: 500 }
      );
    }

    return NextResponse.json({
      date: today,
      count: count || 0,
      hasAutoGenerated: (count || 0) > 0
    });

  } catch (error) {
    console.error('检查今日自动生成记录失败:', error);
    return NextResponse.json(
      { error: '服务器错误' },
      { status: 500 }
    );
  }
}