/**
 * 交易 API 服务
 */

import { apiClient, buildQueryString } from '../client';
import type { Transaction } from '@/types/domain/transaction';

/**
 * 交易列表查询参数
 */
export interface TransactionListParams {
  month?: string;
  range?: string;
  startDate?: string;
  endDate?: string;
  start_date?: string;
  end_date?: string;
  type?: 'income' | 'expense';
  page_size?: number;
  page?: number;
}

/**
 * 创建交易参数
 */
export interface CreateTransactionParams {
  type: 'income' | 'expense';
  category: string;
  subcategory?: string;
  amount: number;
  note?: string;
  date: string;
  currency?: string;
  paymentMethodId?: string;
}

/**
 * 更新交易参数
 */
export interface UpdateTransactionParams extends Partial<CreateTransactionParams> {
  id: string;
}

/**
 * 交易列表响应
 */
export interface TransactionListResponse {
  data?: Transaction[];
  transactions?: Transaction[];
  total?: number;
}

/**
 * 交易 API 服务
 */
export const transactionsApi = {
  /**
   * 获取交易列表
   */
  list(params?: TransactionListParams): Promise<TransactionListResponse> {
    const query = buildQueryString(params || {});
    return apiClient.get<TransactionListResponse>(`/api/transactions${query}`);
  },

  /**
   * 获取单个交易
   */
  get(id: string): Promise<Transaction> {
    return apiClient.get<Transaction>(`/api/transactions/${id}`);
  },

  /**
   * 创建交易
   */
  create(data: CreateTransactionParams): Promise<Transaction> {
    return apiClient.post<Transaction>('/api/transactions', data);
  },

  /**
   * 更新交易
   */
  update({ id, ...data }: UpdateTransactionParams): Promise<Transaction> {
    return apiClient.put<Transaction>(`/api/transactions/${id}`, data);
  },

  /**
   * 删除交易
   */
  delete(id: string): Promise<void> {
    return apiClient.delete<void>(`/api/transactions/${id}`);
  },

  /**
   * 恢复已删除的交易
   */
  restore(id: string): Promise<Transaction> {
    return apiClient.post<Transaction>(`/api/transactions/${id}/restore`);
  },

  /**
   * 获取今日自动生成的交易
   */
  getTodayAutoGenerated(): Promise<Transaction[]> {
    return apiClient.get<Transaction[]>('/api/transactions/today-auto-generated');
  },
};
