name: Deploy to Local Server

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Export deploy metadata
        run: |
          echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "Deploy commit: ${GITHUB_SHA}"

      - name: Run Docker Deploy
        env:
          DEPLOY_ENV_SOURCE: /home/heyanxiao/project/smart-ledger/.env.local
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh
